/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AlunoAcessibilidadeRouteImport } from './routes/aluno/acessibilidade'
import { Route as AlunoApoioRouteImport } from './routes/aluno/apoio'
import { Route as AlunoChatRouteImport } from './routes/aluno/chat'
import { Route as AlunoChatIaRouteImport } from './routes/aluno/chat-ia'
import { Route as AlunoConfidenteRouteImport } from './routes/aluno/confidente'
import { Route as AlunoDiarioRouteImport } from './routes/aluno/diario'
import { Route as AlunoHomeRouteImport } from './routes/aluno/home'
import { Route as AlunoTurmaRouteImport } from './routes/aluno/turma'
import { Route as DirecaoAcessibilidadeRouteImport } from './routes/direcao/acessibilidade'
import { Route as DirecaoAnoLetivoRouteImport } from './routes/direcao/ano-letivo'
import { Route as DirecaoConfiguracoesRouteImport } from './routes/direcao/configuracoes'
import { Route as DirecaoConselhoTutelarRouteImport } from './routes/direcao/conselho-tutelar'
import { Route as DirecaoDenunciasRouteImport } from './routes/direcao/denuncias'
import { Route as DirecaoEspecialistaRouteImport } from './routes/direcao/especialista'
import { Route as DirecaoFamiliaRouteImport } from './routes/direcao/familia'
import { Route as DirecaoLgpdRouteImport } from './routes/direcao/lgpd'
import { Route as DirecaoMapaCalorRouteImport } from './routes/direcao/mapa-calor'
import { Route as DirecaoPainelRouteImport } from './routes/direcao/painel'
import { Route as DirecaoProtocolosRouteImport } from './routes/direcao/protocolos'
import { Route as DirecaoTurmasRouteImport } from './routes/direcao/turmas'
import { Route as FamiliaIndexRouteImport } from './routes/familia/index'
import { Route as FamiliaBemEstarRouteImport } from './routes/familia/bem-estar'
import { Route as FamiliaFrequenciaRouteImport } from './routes/familia/frequencia'
import { Route as FamiliaNotasRouteImport } from './routes/familia/notas'
import { Route as FamiliaPainelRouteImport } from './routes/familia/painel'
import { Route as ProfessorAcessibilidadeRouteImport } from './routes/professor/acessibilidade'
import { Route as ProfessorAlertasRouteImport } from './routes/professor/alertas'
import { Route as ProfessorAnoLetivoRouteImport } from './routes/professor/ano-letivo'
import { Route as ProfessorBibliotecaRouteImport } from './routes/professor/biblioteca'
import { Route as ProfessorConselhoTutelarRouteImport } from './routes/professor/conselho-tutelar'
import { Route as ProfessorDashboardRouteImport } from './routes/professor/dashboard'
import { Route as ProfessorDenunciasRouteImport } from './routes/professor/denuncias'
import { Route as ProfessorEspecialistaRouteImport } from './routes/professor/especialista'
import { Route as ProfessorFamiliaRouteImport } from './routes/professor/familia'
import { Route as ProfessorPlanoIndividualRouteImport } from './routes/professor/plano-individual'
import { Route as ProfessorRelatorioRouteImport } from './routes/professor/relatorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoAcessibilidadeRoute = AlunoAcessibilidadeRouteImport.update({
  id: '/aluno/acessibilidade',
  path: '/aluno/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoApoioRoute = AlunoApoioRouteImport.update({
  id: '/aluno/apoio',
  path: '/aluno/apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoChatRoute = AlunoChatRouteImport.update({
  id: '/aluno/chat',
  path: '/aluno/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoChatIaRoute = AlunoChatIaRouteImport.update({
  id: '/aluno/chat-ia',
  path: '/aluno/chat-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoConfidenteRoute = AlunoConfidenteRouteImport.update({
  id: '/aluno/confidente',
  path: '/aluno/confidente',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoDiarioRoute = AlunoDiarioRouteImport.update({
  id: '/aluno/diario',
  path: '/aluno/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoHomeRoute = AlunoHomeRouteImport.update({
  id: '/aluno/home',
  path: '/aluno/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoTurmaRoute = AlunoTurmaRouteImport.update({
  id: '/aluno/turma',
  path: '/aluno/turma',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoAcessibilidadeRoute = DirecaoAcessibilidadeRouteImport.update({
  id: '/direcao/acessibilidade',
  path: '/direcao/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoAnoLetivoRoute = DirecaoAnoLetivoRouteImport.update({
  id: '/direcao/ano-letivo',
  path: '/direcao/ano-letivo',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoConfiguracoesRoute = DirecaoConfiguracoesRouteImport.update({
  id: '/direcao/configuracoes',
  path: '/direcao/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoConselhoTutelarRoute = DirecaoConselhoTutelarRouteImport.update({
  id: '/direcao/conselho-tutelar',
  path: '/direcao/conselho-tutelar',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoDenunciasRoute = DirecaoDenunciasRouteImport.update({
  id: '/direcao/denuncias',
  path: '/direcao/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoEspecialistaRoute = DirecaoEspecialistaRouteImport.update({
  id: '/direcao/especialista',
  path: '/direcao/especialista',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoFamiliaRoute = DirecaoFamiliaRouteImport.update({
  id: '/direcao/familia',
  path: '/direcao/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoLgpdRoute = DirecaoLgpdRouteImport.update({
  id: '/direcao/lgpd',
  path: '/direcao/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoMapaCalorRoute = DirecaoMapaCalorRouteImport.update({
  id: '/direcao/mapa-calor',
  path: '/direcao/mapa-calor',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoPainelRoute = DirecaoPainelRouteImport.update({
  id: '/direcao/painel',
  path: '/direcao/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoProtocolosRoute = DirecaoProtocolosRouteImport.update({
  id: '/direcao/protocolos',
  path: '/direcao/protocolos',
  getParentRoute: () => rootRouteImport,
} as any)
const DirecaoTurmasRoute = DirecaoTurmasRouteImport.update({
  id: '/direcao/turmas',
  path: '/direcao/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaIndexRoute = FamiliaIndexRouteImport.update({
  id: '/familia/',
  path: '/familia/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaBemEstarRoute = FamiliaBemEstarRouteImport.update({
  id: '/familia/bem-estar',
  path: '/familia/bem-estar',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaFrequenciaRoute = FamiliaFrequenciaRouteImport.update({
  id: '/familia/frequencia',
  path: '/familia/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaNotasRoute = FamiliaNotasRouteImport.update({
  id: '/familia/notas',
  path: '/familia/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaPainelRoute = FamiliaPainelRouteImport.update({
  id: '/familia/painel',
  path: '/familia/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorAcessibilidadeRoute = ProfessorAcessibilidadeRouteImport.update({
  id: '/professor/acessibilidade',
  path: '/professor/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorAlertasRoute = ProfessorAlertasRouteImport.update({
  id: '/professor/alertas',
  path: '/professor/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorAnoLetivoRoute = ProfessorAnoLetivoRouteImport.update({
  id: '/professor/ano-letivo',
  path: '/professor/ano-letivo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorBibliotecaRoute = ProfessorBibliotecaRouteImport.update({
  id: '/professor/biblioteca',
  path: '/professor/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorConselhoTutelarRoute =
  ProfessorConselhoTutelarRouteImport.update({
    id: '/professor/conselho-tutelar',
    path: '/professor/conselho-tutelar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessorDashboardRoute = ProfessorDashboardRouteImport.update({
  id: '/professor/dashboard',
  path: '/professor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorDenunciasRoute = ProfessorDenunciasRouteImport.update({
  id: '/professor/denuncias',
  path: '/professor/denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorEspecialistaRoute = ProfessorEspecialistaRouteImport.update({
  id: '/professor/especialista',
  path: '/professor/especialista',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorFamiliaRoute = ProfessorFamiliaRouteImport.update({
  id: '/professor/familia',
  path: '/professor/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorPlanoIndividualRoute =
  ProfessorPlanoIndividualRouteImport.update({
    id: '/professor/plano-individual',
    path: '/professor/plano-individual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessorRelatorioRoute = ProfessorRelatorioRouteImport.update({
  id: '/professor/relatorio',
  path: '/professor/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/brand': typeof BrandRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/aluno/acessibilidade': typeof AlunoAcessibilidadeRoute
  '/aluno/apoio': typeof AlunoApoioRoute
  '/aluno/chat': typeof AlunoChatRoute
  '/aluno/chat-ia': typeof AlunoChatIaRoute
  '/aluno/confidente': typeof AlunoConfidenteRoute
  '/aluno/diario': typeof AlunoDiarioRoute
  '/aluno/home': typeof AlunoHomeRoute
  '/aluno/turma': typeof AlunoTurmaRoute
  '/direcao/acessibilidade': typeof DirecaoAcessibilidadeRoute
  '/direcao/ano-letivo': typeof DirecaoAnoLetivoRoute
  '/direcao/configuracoes': typeof DirecaoConfiguracoesRoute
  '/direcao/conselho-tutelar': typeof DirecaoConselhoTutelarRoute
  '/direcao/denuncias': typeof DirecaoDenunciasRoute
  '/direcao/especialista': typeof DirecaoEspecialistaRoute
  '/direcao/familia': typeof DirecaoFamiliaRoute
  '/direcao/lgpd': typeof DirecaoLgpdRoute
  '/direcao/mapa-calor': typeof DirecaoMapaCalorRoute
  '/direcao/painel': typeof DirecaoPainelRoute
  '/direcao/protocolos': typeof DirecaoProtocolosRoute
  '/direcao/turmas': typeof DirecaoTurmasRoute
  '/familia/bem-estar': typeof FamiliaBemEstarRoute
  '/familia/frequencia': typeof FamiliaFrequenciaRoute
  '/familia/notas': typeof FamiliaNotasRoute
  '/familia/painel': typeof FamiliaPainelRoute
  '/professor/acessibilidade': typeof ProfessorAcessibilidadeRoute
  '/professor/alertas': typeof ProfessorAlertasRoute
  '/professor/ano-letivo': typeof ProfessorAnoLetivoRoute
  '/professor/biblioteca': typeof ProfessorBibliotecaRoute
  '/professor/conselho-tutelar': typeof ProfessorConselhoTutelarRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/denuncias': typeof ProfessorDenunciasRoute
  '/professor/especialista': typeof ProfessorEspecialistaRoute
  '/professor/familia': typeof ProfessorFamiliaRoute
  '/professor/plano-individual': typeof ProfessorPlanoIndividualRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/familia/': typeof FamiliaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/brand': typeof BrandRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/aluno/acessibilidade': typeof AlunoAcessibilidadeRoute
  '/aluno/apoio': typeof AlunoApoioRoute
  '/aluno/chat': typeof AlunoChatRoute
  '/aluno/chat-ia': typeof AlunoChatIaRoute
  '/aluno/confidente': typeof AlunoConfidenteRoute
  '/aluno/diario': typeof AlunoDiarioRoute
  '/aluno/home': typeof AlunoHomeRoute
  '/aluno/turma': typeof AlunoTurmaRoute
  '/direcao/acessibilidade': typeof DirecaoAcessibilidadeRoute
  '/direcao/ano-letivo': typeof DirecaoAnoLetivoRoute
  '/direcao/configuracoes': typeof DirecaoConfiguracoesRoute
  '/direcao/conselho-tutelar': typeof DirecaoConselhoTutelarRoute
  '/direcao/denuncias': typeof DirecaoDenunciasRoute
  '/direcao/especialista': typeof DirecaoEspecialistaRoute
  '/direcao/familia': typeof DirecaoFamiliaRoute
  '/direcao/lgpd': typeof DirecaoLgpdRoute
  '/direcao/mapa-calor': typeof DirecaoMapaCalorRoute
  '/direcao/painel': typeof DirecaoPainelRoute
  '/direcao/protocolos': typeof DirecaoProtocolosRoute
  '/direcao/turmas': typeof DirecaoTurmasRoute
  '/familia/bem-estar': typeof FamiliaBemEstarRoute
  '/familia/frequencia': typeof FamiliaFrequenciaRoute
  '/familia/notas': typeof FamiliaNotasRoute
  '/familia/painel': typeof FamiliaPainelRoute
  '/professor/acessibilidade': typeof ProfessorAcessibilidadeRoute
  '/professor/alertas': typeof ProfessorAlertasRoute
  '/professor/ano-letivo': typeof ProfessorAnoLetivoRoute
  '/professor/biblioteca': typeof ProfessorBibliotecaRoute
  '/professor/conselho-tutelar': typeof ProfessorConselhoTutelarRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/denuncias': typeof ProfessorDenunciasRoute
  '/professor/especialista': typeof ProfessorEspecialistaRoute
  '/professor/familia': typeof ProfessorFamiliaRoute
  '/professor/plano-individual': typeof ProfessorPlanoIndividualRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/familia': typeof FamiliaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bem-vindo': typeof BemVindoRoute
  '/brand': typeof BrandRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/aluno/acessibilidade': typeof AlunoAcessibilidadeRoute
  '/aluno/apoio': typeof AlunoApoioRoute
  '/aluno/chat': typeof AlunoChatRoute
  '/aluno/chat-ia': typeof AlunoChatIaRoute
  '/aluno/confidente': typeof AlunoConfidenteRoute
  '/aluno/diario': typeof AlunoDiarioRoute
  '/aluno/home': typeof AlunoHomeRoute
  '/aluno/turma': typeof AlunoTurmaRoute
  '/direcao/acessibilidade': typeof DirecaoAcessibilidadeRoute
  '/direcao/ano-letivo': typeof DirecaoAnoLetivoRoute
  '/direcao/configuracoes': typeof DirecaoConfiguracoesRoute
  '/direcao/conselho-tutelar': typeof DirecaoConselhoTutelarRoute
  '/direcao/denuncias': typeof DirecaoDenunciasRoute
  '/direcao/especialista': typeof DirecaoEspecialistaRoute
  '/direcao/familia': typeof DirecaoFamiliaRoute
  '/direcao/lgpd': typeof DirecaoLgpdRoute
  '/direcao/mapa-calor': typeof DirecaoMapaCalorRoute
  '/direcao/painel': typeof DirecaoPainelRoute
  '/direcao/protocolos': typeof DirecaoProtocolosRoute
  '/direcao/turmas': typeof DirecaoTurmasRoute
  '/familia/bem-estar': typeof FamiliaBemEstarRoute
  '/familia/frequencia': typeof FamiliaFrequenciaRoute
  '/familia/notas': typeof FamiliaNotasRoute
  '/familia/painel': typeof FamiliaPainelRoute
  '/professor/acessibilidade': typeof ProfessorAcessibilidadeRoute
  '/professor/alertas': typeof ProfessorAlertasRoute
  '/professor/ano-letivo': typeof ProfessorAnoLetivoRoute
  '/professor/biblioteca': typeof ProfessorBibliotecaRoute
  '/professor/conselho-tutelar': typeof ProfessorConselhoTutelarRoute
  '/professor/dashboard': typeof ProfessorDashboardRoute
  '/professor/denuncias': typeof ProfessorDenunciasRoute
  '/professor/especialista': typeof ProfessorEspecialistaRoute
  '/professor/familia': typeof ProfessorFamiliaRoute
  '/professor/plano-individual': typeof ProfessorPlanoIndividualRoute
  '/professor/relatorio': typeof ProfessorRelatorioRoute
  '/familia/': typeof FamiliaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bem-vindo'
    | '/brand'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/aluno/acessibilidade'
    | '/aluno/apoio'
    | '/aluno/chat'
    | '/aluno/chat-ia'
    | '/aluno/confidente'
    | '/aluno/diario'
    | '/aluno/home'
    | '/aluno/turma'
    | '/direcao/acessibilidade'
    | '/direcao/ano-letivo'
    | '/direcao/configuracoes'
    | '/direcao/conselho-tutelar'
    | '/direcao/denuncias'
    | '/direcao/especialista'
    | '/direcao/familia'
    | '/direcao/lgpd'
    | '/direcao/mapa-calor'
    | '/direcao/painel'
    | '/direcao/protocolos'
    | '/direcao/turmas'
    | '/familia/bem-estar'
    | '/familia/frequencia'
    | '/familia/notas'
    | '/familia/painel'
    | '/professor/acessibilidade'
    | '/professor/alertas'
    | '/professor/ano-letivo'
    | '/professor/biblioteca'
    | '/professor/conselho-tutelar'
    | '/professor/dashboard'
    | '/professor/denuncias'
    | '/professor/especialista'
    | '/professor/familia'
    | '/professor/plano-individual'
    | '/professor/relatorio'
    | '/familia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bem-vindo'
    | '/brand'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/aluno/acessibilidade'
    | '/aluno/apoio'
    | '/aluno/chat'
    | '/aluno/chat-ia'
    | '/aluno/confidente'
    | '/aluno/diario'
    | '/aluno/home'
    | '/aluno/turma'
    | '/direcao/acessibilidade'
    | '/direcao/ano-letivo'
    | '/direcao/configuracoes'
    | '/direcao/conselho-tutelar'
    | '/direcao/denuncias'
    | '/direcao/especialista'
    | '/direcao/familia'
    | '/direcao/lgpd'
    | '/direcao/mapa-calor'
    | '/direcao/painel'
    | '/direcao/protocolos'
    | '/direcao/turmas'
    | '/familia/bem-estar'
    | '/familia/frequencia'
    | '/familia/notas'
    | '/familia/painel'
    | '/professor/acessibilidade'
    | '/professor/alertas'
    | '/professor/ano-letivo'
    | '/professor/biblioteca'
    | '/professor/conselho-tutelar'
    | '/professor/dashboard'
    | '/professor/denuncias'
    | '/professor/especialista'
    | '/professor/familia'
    | '/professor/plano-individual'
    | '/professor/relatorio'
    | '/familia'
  id:
    | '__root__'
    | '/'
    | '/bem-vindo'
    | '/brand'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/aluno/acessibilidade'
    | '/aluno/apoio'
    | '/aluno/chat'
    | '/aluno/chat-ia'
    | '/aluno/confidente'
    | '/aluno/diario'
    | '/aluno/home'
    | '/aluno/turma'
    | '/direcao/acessibilidade'
    | '/direcao/ano-letivo'
    | '/direcao/configuracoes'
    | '/direcao/conselho-tutelar'
    | '/direcao/denuncias'
    | '/direcao/especialista'
    | '/direcao/familia'
    | '/direcao/lgpd'
    | '/direcao/mapa-calor'
    | '/direcao/painel'
    | '/direcao/protocolos'
    | '/direcao/turmas'
    | '/familia/bem-estar'
    | '/familia/frequencia'
    | '/familia/notas'
    | '/familia/painel'
    | '/professor/acessibilidade'
    | '/professor/alertas'
    | '/professor/ano-letivo'
    | '/professor/biblioteca'
    | '/professor/conselho-tutelar'
    | '/professor/dashboard'
    | '/professor/denuncias'
    | '/professor/especialista'
    | '/professor/familia'
    | '/professor/plano-individual'
    | '/professor/relatorio'
    | '/familia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BemVindoRoute: typeof BemVindoRoute
  BrandRoute: typeof BrandRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  AlunoAcessibilidadeRoute: typeof AlunoAcessibilidadeRoute
  AlunoApoioRoute: typeof AlunoApoioRoute
  AlunoChatRoute: typeof AlunoChatRoute
  AlunoChatIaRoute: typeof AlunoChatIaRoute
  AlunoConfidenteRoute: typeof AlunoConfidenteRoute
  AlunoDiarioRoute: typeof AlunoDiarioRoute
  AlunoHomeRoute: typeof AlunoHomeRoute
  AlunoTurmaRoute: typeof AlunoTurmaRoute
  DirecaoAcessibilidadeRoute: typeof DirecaoAcessibilidadeRoute
  DirecaoAnoLetivoRoute: typeof DirecaoAnoLetivoRoute
  DirecaoConfiguracoesRoute: typeof DirecaoConfiguracoesRoute
  DirecaoConselhoTutelarRoute: typeof DirecaoConselhoTutelarRoute
  DirecaoDenunciasRoute: typeof DirecaoDenunciasRoute
  DirecaoEspecialistaRoute: typeof DirecaoEspecialistaRoute
  DirecaoFamiliaRoute: typeof DirecaoFamiliaRoute
  DirecaoLgpdRoute: typeof DirecaoLgpdRoute
  DirecaoMapaCalorRoute: typeof DirecaoMapaCalorRoute
  DirecaoPainelRoute: typeof DirecaoPainelRoute
  DirecaoProtocolosRoute: typeof DirecaoProtocolosRoute
  DirecaoTurmasRoute: typeof DirecaoTurmasRoute
  FamiliaBemEstarRoute: typeof FamiliaBemEstarRoute
  FamiliaFrequenciaRoute: typeof FamiliaFrequenciaRoute
  FamiliaNotasRoute: typeof FamiliaNotasRoute
  FamiliaPainelRoute: typeof FamiliaPainelRoute
  ProfessorAcessibilidadeRoute: typeof ProfessorAcessibilidadeRoute
  ProfessorAlertasRoute: typeof ProfessorAlertasRoute
  ProfessorAnoLetivoRoute: typeof ProfessorAnoLetivoRoute
  ProfessorBibliotecaRoute: typeof ProfessorBibliotecaRoute
  ProfessorConselhoTutelarRoute: typeof ProfessorConselhoTutelarRoute
  ProfessorDashboardRoute: typeof ProfessorDashboardRoute
  ProfessorDenunciasRoute: typeof ProfessorDenunciasRoute
  ProfessorEspecialistaRoute: typeof ProfessorEspecialistaRoute
  ProfessorFamiliaRoute: typeof ProfessorFamiliaRoute
  ProfessorPlanoIndividualRoute: typeof ProfessorPlanoIndividualRoute
  ProfessorRelatorioRoute: typeof ProfessorRelatorioRoute
  FamiliaIndexRoute: typeof FamiliaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/acessibilidade': {
      id: '/aluno/acessibilidade'
      path: '/aluno/acessibilidade'
      fullPath: '/aluno/acessibilidade'
      preLoaderRoute: typeof AlunoAcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/apoio': {
      id: '/aluno/apoio'
      path: '/aluno/apoio'
      fullPath: '/aluno/apoio'
      preLoaderRoute: typeof AlunoApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/chat': {
      id: '/aluno/chat'
      path: '/aluno/chat'
      fullPath: '/aluno/chat'
      preLoaderRoute: typeof AlunoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/chat-ia': {
      id: '/aluno/chat-ia'
      path: '/aluno/chat-ia'
      fullPath: '/aluno/chat-ia'
      preLoaderRoute: typeof AlunoChatIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/confidente': {
      id: '/aluno/confidente'
      path: '/aluno/confidente'
      fullPath: '/aluno/confidente'
      preLoaderRoute: typeof AlunoConfidenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/diario': {
      id: '/aluno/diario'
      path: '/aluno/diario'
      fullPath: '/aluno/diario'
      preLoaderRoute: typeof AlunoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/home': {
      id: '/aluno/home'
      path: '/aluno/home'
      fullPath: '/aluno/home'
      preLoaderRoute: typeof AlunoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno/turma': {
      id: '/aluno/turma'
      path: '/aluno/turma'
      fullPath: '/aluno/turma'
      preLoaderRoute: typeof AlunoTurmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/acessibilidade': {
      id: '/direcao/acessibilidade'
      path: '/direcao/acessibilidade'
      fullPath: '/direcao/acessibilidade'
      preLoaderRoute: typeof DirecaoAcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/ano-letivo': {
      id: '/direcao/ano-letivo'
      path: '/direcao/ano-letivo'
      fullPath: '/direcao/ano-letivo'
      preLoaderRoute: typeof DirecaoAnoLetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/configuracoes': {
      id: '/direcao/configuracoes'
      path: '/direcao/configuracoes'
      fullPath: '/direcao/configuracoes'
      preLoaderRoute: typeof DirecaoConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/conselho-tutelar': {
      id: '/direcao/conselho-tutelar'
      path: '/direcao/conselho-tutelar'
      fullPath: '/direcao/conselho-tutelar'
      preLoaderRoute: typeof DirecaoConselhoTutelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/denuncias': {
      id: '/direcao/denuncias'
      path: '/direcao/denuncias'
      fullPath: '/direcao/denuncias'
      preLoaderRoute: typeof DirecaoDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/especialista': {
      id: '/direcao/especialista'
      path: '/direcao/especialista'
      fullPath: '/direcao/especialista'
      preLoaderRoute: typeof DirecaoEspecialistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/familia': {
      id: '/direcao/familia'
      path: '/direcao/familia'
      fullPath: '/direcao/familia'
      preLoaderRoute: typeof DirecaoFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/lgpd': {
      id: '/direcao/lgpd'
      path: '/direcao/lgpd'
      fullPath: '/direcao/lgpd'
      preLoaderRoute: typeof DirecaoLgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/mapa-calor': {
      id: '/direcao/mapa-calor'
      path: '/direcao/mapa-calor'
      fullPath: '/direcao/mapa-calor'
      preLoaderRoute: typeof DirecaoMapaCalorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/painel': {
      id: '/direcao/painel'
      path: '/direcao/painel'
      fullPath: '/direcao/painel'
      preLoaderRoute: typeof DirecaoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/protocolos': {
      id: '/direcao/protocolos'
      path: '/direcao/protocolos'
      fullPath: '/direcao/protocolos'
      preLoaderRoute: typeof DirecaoProtocolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direcao/turmas': {
      id: '/direcao/turmas'
      path: '/direcao/turmas'
      fullPath: '/direcao/turmas'
      preLoaderRoute: typeof DirecaoTurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/': {
      id: '/familia/'
      path: '/familia'
      fullPath: '/familia/'
      preLoaderRoute: typeof FamiliaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/bem-estar': {
      id: '/familia/bem-estar'
      path: '/familia/bem-estar'
      fullPath: '/familia/bem-estar'
      preLoaderRoute: typeof FamiliaBemEstarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/frequencia': {
      id: '/familia/frequencia'
      path: '/familia/frequencia'
      fullPath: '/familia/frequencia'
      preLoaderRoute: typeof FamiliaFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/notas': {
      id: '/familia/notas'
      path: '/familia/notas'
      fullPath: '/familia/notas'
      preLoaderRoute: typeof FamiliaNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/painel': {
      id: '/familia/painel'
      path: '/familia/painel'
      fullPath: '/familia/painel'
      preLoaderRoute: typeof FamiliaPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/acessibilidade': {
      id: '/professor/acessibilidade'
      path: '/professor/acessibilidade'
      fullPath: '/professor/acessibilidade'
      preLoaderRoute: typeof ProfessorAcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/alertas': {
      id: '/professor/alertas'
      path: '/professor/alertas'
      fullPath: '/professor/alertas'
      preLoaderRoute: typeof ProfessorAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/ano-letivo': {
      id: '/professor/ano-letivo'
      path: '/professor/ano-letivo'
      fullPath: '/professor/ano-letivo'
      preLoaderRoute: typeof ProfessorAnoLetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/biblioteca': {
      id: '/professor/biblioteca'
      path: '/professor/biblioteca'
      fullPath: '/professor/biblioteca'
      preLoaderRoute: typeof ProfessorBibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/conselho-tutelar': {
      id: '/professor/conselho-tutelar'
      path: '/professor/conselho-tutelar'
      fullPath: '/professor/conselho-tutelar'
      preLoaderRoute: typeof ProfessorConselhoTutelarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/dashboard': {
      id: '/professor/dashboard'
      path: '/professor/dashboard'
      fullPath: '/professor/dashboard'
      preLoaderRoute: typeof ProfessorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/denuncias': {
      id: '/professor/denuncias'
      path: '/professor/denuncias'
      fullPath: '/professor/denuncias'
      preLoaderRoute: typeof ProfessorDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/especialista': {
      id: '/professor/especialista'
      path: '/professor/especialista'
      fullPath: '/professor/especialista'
      preLoaderRoute: typeof ProfessorEspecialistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/familia': {
      id: '/professor/familia'
      path: '/professor/familia'
      fullPath: '/professor/familia'
      preLoaderRoute: typeof ProfessorFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/plano-individual': {
      id: '/professor/plano-individual'
      path: '/professor/plano-individual'
      fullPath: '/professor/plano-individual'
      preLoaderRoute: typeof ProfessorPlanoIndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/relatorio': {
      id: '/professor/relatorio'
      path: '/professor/relatorio'
      fullPath: '/professor/relatorio'
      preLoaderRoute: typeof ProfessorRelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BemVindoRoute: BemVindoRoute,
  BrandRoute: BrandRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  AlunoAcessibilidadeRoute: AlunoAcessibilidadeRoute,
  AlunoApoioRoute: AlunoApoioRoute,
  AlunoChatRoute: AlunoChatRoute,
  AlunoChatIaRoute: AlunoChatIaRoute,
  AlunoConfidenteRoute: AlunoConfidenteRoute,
  AlunoDiarioRoute: AlunoDiarioRoute,
  AlunoHomeRoute: AlunoHomeRoute,
  AlunoTurmaRoute: AlunoTurmaRoute,
  DirecaoAcessibilidadeRoute: DirecaoAcessibilidadeRoute,
  DirecaoAnoLetivoRoute: DirecaoAnoLetivoRoute,
  DirecaoConfiguracoesRoute: DirecaoConfiguracoesRoute,
  DirecaoConselhoTutelarRoute: DirecaoConselhoTutelarRoute,
  DirecaoDenunciasRoute: DirecaoDenunciasRoute,
  DirecaoEspecialistaRoute: DirecaoEspecialistaRoute,
  DirecaoFamiliaRoute: DirecaoFamiliaRoute,
  DirecaoLgpdRoute: DirecaoLgpdRoute,
  DirecaoMapaCalorRoute: DirecaoMapaCalorRoute,
  DirecaoPainelRoute: DirecaoPainelRoute,
  DirecaoProtocolosRoute: DirecaoProtocolosRoute,
  DirecaoTurmasRoute: DirecaoTurmasRoute,
  FamiliaBemEstarRoute: FamiliaBemEstarRoute,
  FamiliaFrequenciaRoute: FamiliaFrequenciaRoute,
  FamiliaNotasRoute: FamiliaNotasRoute,
  FamiliaPainelRoute: FamiliaPainelRoute,
  ProfessorAcessibilidadeRoute: ProfessorAcessibilidadeRoute,
  ProfessorAlertasRoute: ProfessorAlertasRoute,
  ProfessorAnoLetivoRoute: ProfessorAnoLetivoRoute,
  ProfessorBibliotecaRoute: ProfessorBibliotecaRoute,
  ProfessorConselhoTutelarRoute: ProfessorConselhoTutelarRoute,
  ProfessorDashboardRoute: ProfessorDashboardRoute,
  ProfessorDenunciasRoute: ProfessorDenunciasRoute,
  ProfessorEspecialistaRoute: ProfessorEspecialistaRoute,
  ProfessorFamiliaRoute: ProfessorFamiliaRoute,
  ProfessorPlanoIndividualRoute: ProfessorPlanoIndividualRoute,
  ProfessorRelatorioRoute: ProfessorRelatorioRoute,
  FamiliaIndexRoute: FamiliaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
